version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: github.com/onsi/ginkgo
    versions:
    - 1.14.2
    - 1.15.0
    - 1.15.1
    - 1.15.2
    - 1.16.0
  - dependency-name: github.com/a8m/rql
    versions:
    - 1.3.0
  - dependency-name: github.com/onsi/gomega
    versions:
    - 1.10.4
    - 1.10.5
  - dependency-name: github.com/jmoiron/sqlx
    versions:
    - 1.3.1
  - dependency-name: github.com/mattn/go-sqlite3
    versions:
    - 1.14.6
  - dependency-name: github.com/lib/pq
    versions:
    - 1.9.0
  - dependency-name: github.com/apex/log
    versions:
    - 1.9.0
  - dependency-name: github.com/facebookincubator/ent
    versions:
    - 0.3.0
