language: go
go:
  - 1.13.x

services:
  - postgresql
  - mysql

addons:
  postgresql: "9.4"

before_script:
  - mysql -e 'CREATE DATABASE orm;'
  - psql -c 'CREATE DATABASE orm;' -U postgres

install:
  - export PATH=$PATH:$HOME/gopath/bin
  - export GO111MODULE=on
  - go get github.com/onsi/gomega
  - go get github.com/onsi/ginkgo
  - go get github.com/mattn/goveralls
  - go install github.com/onsi/ginkgo/ginkgo
  - go mod download
  - go mod verify

env:
  - TEST_PSQL_URL="postgres://127.0.0.1/orm?sslmode=disable"

script:
  - ginkgo -r -v -covermode=atomic -skipPackage example

after_success:
  - script/cover.sh
  - bash <(curl -s https://codecov.io/bash)
